/** Tab 4 — "How the AI Uses It" pipeline trace data */

export const TRACE_QUERY = 'total spend by generation';

export interface TraceMatch {
  field: string;
  score: number;
  note?: string;
}

export interface TraceStep {
  number: number;
  title: string;
  summary: string;
  matches?: TraceMatch[];
  content: string;
  highlight?: string;
}

export const TRACE_STEPS: TraceStep[] = [
  {
    number: 1,
    title: 'Vocabulary Match',
    summary: '"total spend" → total_billed_business',
    content: 'Vector search scanned enriched descriptions and synonyms...',
    matches: [
      { field: 'total_billed_business', score: 0.96, note: 'synonym: "total spend" — exact match' },
      { field: 'spend_volume_mtd', score: 0.71 },
      { field: 'net_revenue', score: 0.44 },
    ],
    highlight: 'The synonym "total spend" exists because a data steward added it in the enrichment workflow. Without it, vector similarity for "total spend" vs "billed_business" would score 0.41 — below threshold. The query would fail to resolve.',
  },
  {
    number: 2,
    title: 'Graph Validation',
    summary: 'Confirmed: total_billed_business + generation in same explore',
    content: 'MATCH (f1:Field {name: "total_billed_business"})-[:IN_EXPLORE]→(e:Explore)-[:IN_EXPLORE]←(f2:Field {name: "generation"})\nRETURN e.name\n\nResult: explore = "customer_insights" ✓',
  },
  {
    number: 3,
    title: 'Required Filter Injected',
    summary: 'partition_date added automatically',
    content: 'total_billed_business has a required_filter:\n\n"partition_date": "BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY) AND CURRENT_DATE()"\n\nInjected into query automatically. The analyst did not specify a date range.',
    highlight: 'This filter rule was set by the Finance Data Office. Governance, not guesswork.',
  },
  {
    number: 4,
    title: 'SQL Generated by Looker',
    summary: 'Query ready to execute',
    content: `SELECT
  cmdl_card_main.generation,
  SUM(custins_customer_insights_cardmember.total_billed_business_amt)
    AS total_billed_business
FROM
  \`axp-lumid.dw.custins_customer_insights_cardmember\`
    AS custins_customer_insights_cardmember
  JOIN \`axp-lumid.dw.cmdl_card_main\` AS cmdl_card_main
    ON custins_customer_insights_cardmember.cust_ref
       = cmdl_card_main.cust_ref
WHERE
  custins_customer_insights_cardmember.partition_date
    BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)
    AND CURRENT_DATE()
GROUP BY 1
ORDER BY 2 DESC`,
  },
];

export const TRACE_RESULTS = [
  { generation: 'Millennial', total_billed_business: '$2,847,392,140' },
  { generation: 'Gen X', total_billed_business: '$1,923,847,203' },
  { generation: 'Boomer', total_billed_business: '$1,654,209,887' },
  { generation: 'Gen Z', total_billed_business: '$892,451,320' },
  { generation: 'Silent', total_billed_business: '$124,830,092' },
];

export const NO_ENRICHMENT_CALLOUT = {
  without_score: 0.41,
  threshold: 0.85,
  fallback_response: "I couldn't find a metric matching 'total spend'. Did you mean: net_revenue, spend_volume_mtd, or total_transaction_amount?",
  punchline: 'Without enrichment, Cortex is a very expensive keyword search.',
};
