"""Filter resolution for the Cortex retrieval pipeline.

Takes raw extracted filters (field_hint + user values) and resolves them to
LookML-compatible filter expressions ready for Looker query generation.

Resolution strategy (5-pass, stops at first match):
  Pass 1: Exact match against known values (view-namespaced → bare fallback)
  Pass 2: Synonym expansion (SYNONYM_MAP → value map)
  Pass 3: Fuzzy match (Levenshtein distance ≤ 2, min input length 3)
  Pass 4: Embedding similarity (TODO — requires embed_fn from pipeline)
  Pass 5: Pass through with low confidence (flag for user review)

Additional handlers (before the 5-pass cascade):
  - Yesno dimensions: "yes"/"enrolled"/"active" → "Yes"
  - Negation: "not Gold" → operator "-", value "GOLD"
  - Numeric ranges: "between 1000 and 5000" → "[1000,5000]", "> 10000" → ">10000"
  - Time normalization: "Q4 2025" → "2025-10-01 to 2025-12-31"

Namespace architecture (multi-BU safe):
  Value maps are stored with "view_name.dimension_name" composite keys internally
  (_VALUE_MAP_NS) to prevent collisions when multiple BUs define dimensions with
  the same name but different valid values.

  At resolution time, the explore context determines which views are in scope.
  _find_view_for_dim() locates the owning view → namespaced lookup is preferred.
  Falls back to bare-name FILTER_VALUE_MAP (flattened, merged across views).

  Example: card_prod_id exists in both cmdl_card_main and custins, with the same
  values. If BU2 adds a different card_prod_id, the namespaced keys prevent collision.

Auto-derivation (Phase 1 — implemented):
  At import time, loads config/filter_catalog.json (generated by
  `python -m scripts.load_lookml_to_pgvector --mode catalog`).
  Auto-derived values from LookML CASE statements, descriptions, and
  always_filter declarations are merged with hardcoded fallbacks.

  Phase 2 (planned): BQ SELECT DISTINCT for raw-column dims (8/11 gaps).
  Phase 3 (planned): Learning loop from Pass 5 passthrough logs.

Integration point:
  Called from pipeline.py Step 4, AFTER explore selection.
  Resolved filters are attached to PipelineResult alongside scored explores.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# ─── CATALOG LOADING ──────────────────────────────────────────────────
# Priority: auto-derived (from LookML parse) > hardcoded (fallback).
# Auto-derived catalog is generated by:
#   python -m scripts.load_lookml_to_pgvector --mode catalog
# and written to config/filter_catalog.json.

_CATALOG_PATH = Path(__file__).resolve().parents[2] / "config" / "filter_catalog.json"


def _load_catalog() -> dict[str, Any]:
    """Load auto-derived filter catalog from JSON, or empty dict if missing."""
    if not _CATALOG_PATH.exists():
        logger.info("No filter catalog at %s — using hardcoded maps only", _CATALOG_PATH)
        return {}
    try:
        with open(_CATALOG_PATH) as f:
            catalog = json.load(f)
        logger.info(
            "Loaded filter catalog: %d value maps, %d synonym groups, "
            "%d yesno dims, %d partition fields",
            len(catalog.get("value_map", {})),
            len(catalog.get("synonyms", {})),
            len(catalog.get("yesno_dimensions", [])),
            len(catalog.get("partition_fields", {})),
        )
        return catalog
    except Exception as e:
        logger.warning("Failed to load filter catalog: %s — using hardcoded maps only", e)
        return {}


# ─── HARDCODED FALLBACKS (VIEW-NAMESPACED) ────────────────────────────
# Keys are "view_name.dimension_name" to prevent collisions at 3+ BUs.
# These cover raw-column dimensions where LookML has no CASE statement.
# Phase 2 (BQ SELECT DISTINCT) will auto-derive these too.

_HARDCODED_VALUE_MAP_NS: dict[str, dict[str, str]] = {
    # cmdl_card_main — demographics, card attributes
    "cmdl_card_main.generation": {
        "millennials": "Millennial",
        "millennial": "Millennial",
        "gen z": "Gen Z",
        "gen-z": "Gen Z",
        "genz": "Gen Z",
        "gen x": "Gen X",
        "gen-x": "Gen X",
        "genx": "Gen X",
        "baby boomer": "Baby Boomer",
        "baby boomers": "Baby Boomer",
        "boomers": "Baby Boomer",
        "boomer": "Baby Boomer",
    },
    "cmdl_card_main.basic_supp_in": {
        "basic": "B",
        "primary": "B",
        "supplementary": "S",
        "secondary": "S",
        "authorized user": "S",
    },
    "cmdl_card_main.apple_pay_wallet_flag": {
        "yes": "Y",
        "enrolled": "Y",
        "no": "N",
        "not enrolled": "N",
    },
    "cmdl_card_main.afc_enroll_in": {
        "yes": "Y",
        "enrolled": "Y",
        "no": "N",
        "not enrolled": "N",
    },
    "cmdl_card_main.card_prod_id": {
        "platinum": "PLAT",
        "gold": "GOLD",
        "green": "GREEN",
        "centurion": "CENT",
        "blue": "BLUE",
    },
    # custins_customer_insights_cardmember — segments, lifecycle
    "custins_customer_insights_cardmember.bus_seg": {
        "open": "OPEN",
        "small business": "OPEN",
        "consumer": "CPS",
        "consumer personal services": "CPS",
        "cps": "CPS",
        "gcs": "GCS",
        "global commercial services": "GCS",
        "commercial": "GCS",
        "gmns": "GMNS",
        "global merchant network services": "GMNS",
        "merchant": "GMNS",
    },
    "custins_customer_insights_cardmember.basic_cust_noa": {
        "new": "New",
        "organic": "Organic",
        "attrited": "Attrited",
    },
    "custins_customer_insights_cardmember.business_org": {
        "charge": "Charge",
        "lending": "Prop Lending",
        "cobrand": "Cobrand",
        "vpay": "Vpay",
    },
    "custins_customer_insights_cardmember.card_prod_id": {
        "platinum": "PLAT",
        "gold": "GOLD",
        "green": "GREEN",
        "centurion": "CENT",
        "blue": "BLUE",
    },
    # risk_indv_cust — risk attributes
    "risk_indv_cust.rel_type": {
        "revolving": "AA",
        "revolver": "AA",
        "primary account": "AA",
    },
    # tlsarpt_travel_sales — travel attributes
    "tlsarpt_travel_sales.travel_vertical": {
        "vacation": "Vacation",
        "business": "Business",
        "transit": "Transit",
        "luxury": "Luxury",
    },
    "tlsarpt_travel_sales.air_trip_type": {
        "round trip": "Round Trip",
        "one way": "One Way",
        "multi city": "Multi City",
    },
}

_HARDCODED_SYNONYM_MAP: dict[str, dict[str, str]] = {
    "generation": {
        "gen y": "millennial",
        "generation y": "millennial",
        "generation z": "gen z",
        "generation x": "gen x",
        "young professionals": "millennial",
        "young": "millennial",
        "older": "baby boomer",
        "senior": "baby boomer",
    },
    "card_prod_id": {
        "plat": "platinum",
        "premium card": "platinum",
        "entry level": "green",
        "basic card": "green",
        "black card": "centurion",
    },
    "bus_seg": {
        "smb": "small business",
        "enterprise": "gcs",
        "corporate": "gcs",
    },
}

_HARDCODED_PARTITION_FIELDS: dict[str, str] = {
    "finance_cardmember_360": "partition_date",
    "finance_merchant_profitability": "partition_date",
    "finance_travel_sales": "booking_date",
    "finance_card_issuance": "issuance_date",
    "finance_customer_risk": "partition_date",
}

DEFAULT_PARTITION_VALUE = "last 90 days"


# ─── NAMESPACE UTILITIES ─────────────────────────────────────────────

def _flatten_ns_map(ns_map: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    """Flatten view.dim keyed map to bare dim keys, merging across views.

    If two views define the same dimension name, their values are merged
    (both sets of user-term aliases are available via bare lookup).
    """
    flat: dict[str, dict[str, str]] = {}
    for ns_key, values in ns_map.items():
        dim = ns_key.split(".", 1)[1] if "." in ns_key else ns_key
        if dim in flat:
            flat[dim].update(values)
        else:
            flat[dim] = dict(values)
    return flat


def _find_view_for_dim(
    dimension: str,
    explore_name: str,
    explore_views: dict[str, list[str]],
    ns_map: dict[str, dict[str, str]],
) -> str:
    """Find which view in an explore owns a dimension, using the namespaced map.

    Returns the view name if exactly one view in the explore has this dimension.
    Returns "" if ambiguous or unknown (falls back to bare lookup).
    """
    if not explore_name or explore_name not in explore_views:
        return ""
    views_in_explore = explore_views[explore_name]
    matches = [v for v in views_in_explore if f"{v}.{dimension}" in ns_map]
    return matches[0] if len(matches) == 1 else ""


# ─── MERGE: AUTO-DERIVED + HARDCODED ─────────────────────────────────

def _merge_catalogs() -> tuple[
    dict[str, dict[str, str]],  # namespaced value map (view.dim keys)
    dict[str, dict[str, str]],  # flattened value map (bare dim keys, backward compat)
    dict[str, dict[str, str]],  # synonym map
    set[str],                   # yesno dimensions
    dict[str, str],             # partition fields
    dict[str, list[str]],       # explore → views mapping
]:
    """Merge auto-derived catalog over hardcoded fallbacks.

    Value maps are stored view-namespaced (view.dim keys) internally.
    A flattened bare-name map is produced for backward compatibility.
    When view context is available, namespaced lookup is preferred.
    """
    catalog = _load_catalog()

    # ── Namespaced value map: hardcoded base + auto-derived overlay ──
    ns_map = dict(_HARDCODED_VALUE_MAP_NS)
    for ns_key, auto_vals in catalog.get("value_map", {}).items():
        if ns_key in ns_map:
            merged = dict(ns_map[ns_key])
            merged.update(auto_vals)
            ns_map[ns_key] = merged
        else:
            ns_map[ns_key] = dict(auto_vals)

    # ── Flatten to bare-name map for backward compat ──
    flat_map = _flatten_ns_map(ns_map)

    # ── Synonym map: hardcoded (value-level synonyms, bare-keyed) ──
    synonym_map = dict(_HARDCODED_SYNONYM_MAP)

    # ── Yesno dimensions: union ──
    yesno = set(catalog.get("yesno_dimensions", []))
    yesno.update({
        "is_replacement", "is_not_cm_initiated", "is_cm_initiated",
        "is_active_standard", "is_active_premium", "is_dining_at_restaurant",
        "is_cancelled", "has_authorized_users",
    })

    # ── Partition fields: auto-derived wins ──
    partition_fields = dict(_HARDCODED_PARTITION_FIELDS)
    partition_fields.update(catalog.get("partition_fields", {}))

    # ── Explore → views mapping ──
    explore_views = catalog.get("explore_views", {})

    return ns_map, flat_map, synonym_map, yesno, partition_fields, explore_views


# Module-level merge (runs once at import)
(
    _VALUE_MAP_NS,           # view.dim keyed (internal, for namespaced resolution)
    FILTER_VALUE_MAP,        # bare dim keyed (public API, backward compat)
    SYNONYM_MAP,
    YESNO_DIMENSIONS,
    EXPLORE_PARTITION_FIELDS,
    _EXPLORE_VIEWS,          # explore → views mapping (internal)
) = _merge_catalogs()

# Negation prefixes — detected and stripped before value resolution
NEGATION_PREFIXES = ("not ", "no ", "non-", "non ", "excluding ", "exclude ", "except ", "without ")


# ─── DATA STRUCTURES ──────────────────────────────────────────────────

@dataclass
class ResolvedFilter:
    """A single resolved filter ready for Looker query generation."""
    field_name: str           # LookML dimension name (e.g., "generation")
    value: str                # Resolved LookML value (e.g., "Millennial")
    operator: str = "="       # Filter operator ("=", "!=", ">", "<", ">=", "<=", "between")
    resolution_pass: int = 0  # Which pass resolved this (1-5, 0=mandatory)
    original_value: str = ""  # What the user said
    confidence: float = 1.0   # Resolution confidence (1.0 for exact, lower for fuzzy/embedding)
    is_negated: bool = False  # True if user said "not X"


@dataclass
class FilterResolutionResult:
    """Complete filter resolution output for a query."""
    resolved_filters: list[ResolvedFilter] = field(default_factory=list)
    mandatory_filters: list[ResolvedFilter] = field(default_factory=list)
    unresolved: list[dict[str, Any]] = field(default_factory=list)

    def to_looker_filters(self) -> dict[str, str]:
        """Convert to flat dict for Looker MCP query generation.

        Multi-value filters on the same dimension are combined using Looker's
        comma-separated syntax: "GOLD,PLAT" for IN (GOLD, PLAT).
        Negated values use Looker's "-VALUE" prefix: "-GOLD" for NOT GOLD.
        Numeric filters use Looker syntax: ">10000", ">=5000", "[1000, 5000]".
        """
        filters: dict[str, str] = {}
        # Mandatory filters first (partition dates, etc.)
        for f in self.mandatory_filters:
            filters[f.field_name] = f.value
        # Then user-specified filters — accumulate multi-value with comma
        for f in self.resolved_filters:
            # Looker negation syntax: prefix value with "-"
            display_value = f"-{f.value}" if f.is_negated else f.value

            if f.field_name in filters:
                existing = filters[f.field_name]
                if display_value not in existing.split(","):
                    filters[f.field_name] = f"{existing},{display_value}"
            else:
                filters[f.field_name] = display_value
        return filters


# ─── TIME NORMALIZATION ────────────────────────────────────────────────
# Converts natural language time expressions to Looker date filter syntax.
# Looker accepts: "last N days/weeks/months/quarters/years",
#                  "YYYY-MM-DD to YYYY-MM-DD", "this quarter", etc.

# Quarter → month mapping
_QUARTER_MONTHS = {
    "1": (1, 3), "q1": (1, 3),
    "2": (4, 6), "q2": (4, 6),
    "3": (7, 9), "q3": (7, 9),
    "4": (10, 12), "q4": (10, 12),
}

# Patterns for time normalization
_TIME_PATTERNS: list[tuple[re.Pattern, str]] = [
    # "Q4 2025" or "Q4 of 2025" or "4th quarter 2025"
    (re.compile(r"(?:q|quarter\s*)(\d)\s*(?:of\s+)?(\d{4})", re.IGNORECASE), "quarter_year"),
    # "last N days/weeks/months/quarters/years"
    (re.compile(r"last\s+(\d+)\s+(day|week|month|quarter|year)s?", re.IGNORECASE), "relative"),
    # "this quarter/month/year"
    (re.compile(r"this\s+(day|week|month|quarter|year)", re.IGNORECASE), "this_period"),
    # "last quarter/month/year" (without N)
    (re.compile(r"last\s+(day|week|month|quarter|year)$", re.IGNORECASE), "last_period"),
    # "YYYY" alone (full year)
    (re.compile(r"^(\d{4})$"), "full_year"),
    # "YYYY-MM-DD" or "YYYY-MM-DD to YYYY-MM-DD" — already Looker-compatible
    (re.compile(r"\d{4}-\d{2}-\d{2}"), "already_formatted"),
]


def normalize_time_expression(raw: str) -> str:
    """Convert a natural language time expression to Looker date filter syntax.

    Examples:
        "Q4 2025"      → "2025-10-01 to 2025-12-31"
        "last quarter"  → "last 1 quarters"
        "last 6 months" → "last 6 months"  (already Looker-compatible)
        "this year"     → "this year"       (already Looker-compatible)
        "2025"          → "2025-01-01 to 2025-12-31"
    """
    raw_stripped = raw.strip()

    for pattern, pattern_type in _TIME_PATTERNS:
        match = pattern.search(raw_stripped)
        if not match:
            continue

        if pattern_type == "quarter_year":
            quarter = match.group(1).lower()
            year = match.group(2)
            months = _QUARTER_MONTHS.get(quarter) or _QUARTER_MONTHS.get(f"q{quarter}")
            if months:
                start_month, end_month = months
                # Last day of the end month
                if end_month == 12:
                    end_day = 31
                elif end_month in (3, 6, 9):
                    end_day = 30
                else:
                    end_day = 28  # Feb fallback
                return f"{year}-{start_month:02d}-01 to {year}-{end_month:02d}-{end_day:02d}"

        elif pattern_type == "relative":
            # "last 6 months" → "last 6 months" (Looker native)
            n = match.group(1)
            unit = match.group(2).lower()
            # Looker uses plural for N > 1
            unit_plural = f"{unit}s" if int(n) > 1 else f"{unit}s"
            return f"last {n} {unit_plural}"

        elif pattern_type == "this_period":
            period = match.group(1).lower()
            return f"this {period}"

        elif pattern_type == "last_period":
            period = match.group(1).lower()
            return f"last 1 {period}s"

        elif pattern_type == "full_year":
            year = match.group(1)
            return f"{year}-01-01 to {year}-12-31"

        elif pattern_type == "already_formatted":
            return raw_stripped

    # Unrecognized — pass through (Looker may still parse it)
    logger.debug("Time expression not normalized, passing through: %s", raw)
    return raw_stripped


# ─── NUMERIC FILTER HANDLING ──────────────────────────────────────────

# Patterns for numeric filter expressions
_NUMERIC_PATTERNS: list[tuple[re.Pattern, str]] = [
    # "between X and Y" or "from X to Y"
    (re.compile(r"(?:between|from)\s+([\d,.]+)\s+(?:and|to)\s+([\d,.]+)", re.IGNORECASE), "between"),
    # "> X", ">= X", "greater than X", "more than X", "above X", "over X"
    (re.compile(r"(?:>=?|greater\s+than|more\s+than|above|over|exceeds?)\s*([\d,.]+)", re.IGNORECASE), "gt"),
    # "< X", "<= X", "less than X", "under X", "below X"
    (re.compile(r"(?:<=?|less\s+than|under|below)\s*([\d,.]+)", re.IGNORECASE), "lt"),
    # "exactly X" or just a plain number
    (re.compile(r"(?:exactly\s+)?([\d,.]+)$", re.IGNORECASE), "exact"),
]


def resolve_numeric_filter(raw_value: str) -> ResolvedFilter | None:
    """Parse a numeric filter expression into Looker filter syntax.

    Looker numeric filter syntax:
        >10000     greater than
        >=10000    greater than or equal
        <5000      less than
        <=5000     less than or equal
        [1000,5000]  between (inclusive)
        10000      exactly

    Returns None if the input is not a numeric expression.
    """
    raw_stripped = raw_value.strip()

    for pattern, pattern_type in _NUMERIC_PATTERNS:
        match = pattern.search(raw_stripped)
        if not match:
            continue

        if pattern_type == "between":
            low = match.group(1).replace(",", "")
            high = match.group(2).replace(",", "")
            return ResolvedFilter(
                field_name="",  # Set by caller
                value=f"[{low},{high}]",
                operator="between",
                resolution_pass=1,
                original_value=raw_value,
                confidence=0.95,
            )

        elif pattern_type == "gt":
            num = match.group(1).replace(",", "")
            op = ">=" if ">=" in raw_stripped else ">"
            return ResolvedFilter(
                field_name="",
                value=f"{op}{num}",
                operator=op,
                resolution_pass=1,
                original_value=raw_value,
                confidence=0.95,
            )

        elif pattern_type == "lt":
            num = match.group(1).replace(",", "")
            op = "<=" if "<=" in raw_stripped else "<"
            return ResolvedFilter(
                field_name="",
                value=f"{op}{num}",
                operator=op,
                resolution_pass=1,
                original_value=raw_value,
                confidence=0.95,
            )

        elif pattern_type == "exact":
            num = match.group(1).replace(",", "")
            return ResolvedFilter(
                field_name="",
                value=num,
                operator="=",
                resolution_pass=1,
                original_value=raw_value,
                confidence=0.90,
            )

    return None


# ─── NEGATION DETECTION ───────────────────────────────────────────────

def _detect_negation(user_value: str) -> tuple[str, bool]:
    """Detect and strip negation prefixes from a filter value.

    Returns (stripped_value, is_negated).

    Examples:
        "not Gold"       → ("Gold", True)
        "excluding PLAT" → ("PLAT", True)
        "Gold"           → ("Gold", False)
        "non-revolving"  → ("revolving", True)
    """
    user_lower = user_value.lower().strip()
    for prefix in NEGATION_PREFIXES:
        if user_lower.startswith(prefix):
            stripped = user_value.strip()[len(prefix):].strip()
            if stripped:  # Don't return empty string
                return stripped, True
    return user_value, False


# ─── RESOLUTION ENGINE ─────────────────────────────────────────────────

def _levenshtein_distance(s1: str, s2: str) -> int:
    """Compute Levenshtein edit distance between two strings."""
    if len(s1) < len(s2):
        return _levenshtein_distance(s2, s1)
    if len(s2) == 0:
        return len(s1)

    prev_row = list(range(len(s2) + 1))
    for i, c1 in enumerate(s1):
        curr_row = [i + 1]
        for j, c2 in enumerate(s2):
            cost = 0 if c1 == c2 else 1
            curr_row.append(min(
                curr_row[j] + 1,        # insert
                prev_row[j + 1] + 1,    # delete
                prev_row[j] + cost,      # substitute
            ))
        prev_row = curr_row
    return prev_row[-1]


def _get_value_map_for_dim(dimension: str, view_name: str = "") -> dict[str, str]:
    """Get the value map for a dimension, preferring namespaced lookup.

    If view_name is known, look up view.dim in _VALUE_MAP_NS first.
    Always falls back to the bare-name FILTER_VALUE_MAP.
    """
    if view_name:
        ns_key = f"{view_name}.{dimension}"
        ns_vals = _VALUE_MAP_NS.get(ns_key)
        if ns_vals:
            return ns_vals
    return FILTER_VALUE_MAP.get(dimension, {})


def _resolve_value_pass1_exact(
    dimension: str,
    user_value: str,
    view_name: str = "",
) -> ResolvedFilter | None:
    """Pass 1: Exact match against value map (namespaced → bare fallback)."""
    user_lower = user_value.lower().strip()

    vals = _get_value_map_for_dim(dimension, view_name)
    mapped = vals.get(user_lower)
    if mapped:
        logger.debug("Pass 1 (exact): %s=%s → %s", dimension, user_value, mapped)
        return ResolvedFilter(
            field_name=dimension,
            value=mapped,
            resolution_pass=1,
            original_value=user_value,
            confidence=1.0,
        )
    return None


def _resolve_value_pass2_fuzzy(
    dimension: str,
    user_value: str,
    max_distance: int = 2,
    min_input_length: int = 3,
    view_name: str = "",
) -> ResolvedFilter | None:
    """Fuzzy match via Levenshtein distance ≤ max_distance.

    Safety guard: inputs shorter than min_input_length are skipped.
    Short strings have enormous Levenshtein neighborhoods relative to the
    dictionary — "y" is distance 1 from "no" and distance 2 from "yes",
    producing false positives.
    """
    user_lower = user_value.lower().strip()

    if len(user_lower) < min_input_length:
        return None

    vals = _get_value_map_for_dim(dimension, view_name)
    if not vals:
        return None

    best_match: str | None = None
    best_distance = max_distance + 1

    for known_key, known_value in vals.items():
        dist = _levenshtein_distance(user_lower, known_key)
        if dist <= max_distance and dist < best_distance:
            best_distance = dist
            best_match = known_value

    if best_match:
        confidence = 1.0 - (best_distance / max(len(user_lower), 1))
        logger.debug(
            "Fuzzy: %s=%s → %s (distance=%d, confidence=%.2f)",
            dimension, user_value, best_match, best_distance, confidence,
        )
        return ResolvedFilter(
            field_name=dimension,
            value=best_match,
            resolution_pass=3,
            original_value=user_value,
            confidence=max(confidence, 0.5),
        )
    return None


def _resolve_value_pass3_synonym(
    dimension: str,
    user_value: str,
) -> ResolvedFilter | None:
    """Synonym expansion via SYNONYM_MAP → then resolve through value map."""
    user_lower = user_value.lower().strip()

    if dimension not in SYNONYM_MAP:
        return None

    canonical_key = SYNONYM_MAP[dimension].get(user_lower)
    if canonical_key is None:
        return None

    if dimension in FILTER_VALUE_MAP:
        mapped = FILTER_VALUE_MAP[dimension].get(canonical_key)
        if mapped:
            logger.debug(
                "Synonym: %s=%s → '%s' → %s",
                dimension, user_value, canonical_key, mapped,
            )
            return ResolvedFilter(
                field_name=dimension,
                value=mapped,
                resolution_pass=2,
                original_value=user_value,
                confidence=0.85,
            )
    return None


def _resolve_yesno(
    dimension: str,
    user_value: str,
) -> ResolvedFilter | None:
    """Resolve yesno dimension values to Looker's "Yes"/"No" format."""
    if dimension not in YESNO_DIMENSIONS:
        return None

    user_lower = user_value.lower().strip()
    if user_lower in ("yes", "true", "y", "1", "enrolled", "active", "has"):
        return ResolvedFilter(
            field_name=dimension,
            value="Yes",
            resolution_pass=1,
            original_value=user_value,
            confidence=1.0,
        )
    elif user_lower in ("no", "false", "n", "0", "not enrolled", "inactive", "not"):
        return ResolvedFilter(
            field_name=dimension,
            value="No",
            resolution_pass=1,
            original_value=user_value,
            confidence=1.0,
        )
    return None


def resolve_single_value(
    dimension: str,
    user_value: str,
    view_name: str = "",
) -> ResolvedFilter | None:
    """Run resolution on a single (dimension, value) pair.

    Args:
        dimension: LookML dimension name (bare, e.g. "generation")
        user_value: Raw user input (e.g. "millennials", "not Gold")
        view_name: Optional view name for namespaced lookup. When provided,
            resolution prefers view-specific values over bare-name fallback.
            This prevents collisions when multiple BUs define same dimension name.

    Handles negation, numeric expressions, yesno, and the 5-pass cascade.
    """
    # ── Negation detection ──
    stripped_value, is_negated = _detect_negation(user_value)

    # ── Numeric filter check (before categorical resolution) ──
    numeric_result = resolve_numeric_filter(stripped_value)
    if numeric_result:
        numeric_result.field_name = dimension
        numeric_result.is_negated = is_negated
        return numeric_result

    # ── Yesno shortcut ──
    result = _resolve_yesno(dimension, stripped_value)
    if result:
        result.is_negated = is_negated
        return result

    # ── Pass 1: Exact match (namespaced → bare fallback) ──
    result = _resolve_value_pass1_exact(dimension, stripped_value, view_name)
    if result:
        result.is_negated = is_negated
        return result

    # ── Pass 2: Synonym expansion (before fuzzy — domain knowledge > edit distance) ──
    result = _resolve_value_pass3_synonym(dimension, stripped_value)
    if result:
        result.resolution_pass = 2
        result.is_negated = is_negated
        return result

    # ── Pass 3: Fuzzy match (Levenshtein ≤ 2, min length 3) ──
    result = _resolve_value_pass2_fuzzy(dimension, stripped_value, view_name=view_name)
    if result:
        result.resolution_pass = 3
        result.is_negated = is_negated
        return result

    # ── Pass 4: Embedding similarity (TODO) ──

    # ── Pass 5: Passthrough with low confidence ──
    logger.info(
        "All passes failed for %s=%s — passing through as-is",
        dimension, user_value,
    )
    return ResolvedFilter(
        field_name=dimension,
        value=stripped_value,
        resolution_pass=5,
        original_value=user_value,
        confidence=0.3,
        is_negated=is_negated,
    )


# ─── MAIN ENTRY POINTS ────────────────────────────────────────────────

def resolve_filters(
    entities: list[dict[str, Any]],
    explore_name: str,
) -> FilterResolutionResult:
    """Resolve all filters from extracted entities for the selected explore.

    Uses explore context to resolve filter dimensions to the correct view,
    enabling namespaced value map lookups that prevent cross-BU collisions.

    Handles:
    1. Categorical/yesno filters → LookML values (5-pass resolution)
    2. Negation → Looker "-VALUE" syntax
    3. Numeric ranges → Looker ">N", "[N,M]" syntax
    4. Time range → normalized to Looker date syntax + correct partition field
    5. Mandatory partition filter → auto-injected if user didn't specify
    """
    result = FilterResolutionResult()

    for entity in entities:
        entity_type = entity.get("type", "")

        if entity_type == "filter":
            field_hint = entity.get("name", "")
            values = entity.get("values", [])
            operator = entity.get("operator", "=")

            if not field_hint or not values:
                continue

            # Resolve which view in this explore owns this dimension
            view_name = _find_view_for_dim(
                field_hint, explore_name, _EXPLORE_VIEWS, _VALUE_MAP_NS,
            )

            for user_value in values:
                resolved = resolve_single_value(field_hint, str(user_value), view_name)
                if resolved:
                    # Preserve operator from entity extraction if not overridden
                    if resolved.operator == "=" and operator != "=":
                        resolved.operator = operator
                    result.resolved_filters.append(resolved)
                else:
                    result.unresolved.append({
                        "field_hint": field_hint,
                        "value": user_value,
                        "operator": operator,
                    })

        elif entity_type == "time_range":
            time_values = entity.get("values", [])
            if time_values:
                partition_field = EXPLORE_PARTITION_FIELDS.get(
                    explore_name, "partition_date"
                )
                raw_time = str(time_values[0])
                normalized_time = normalize_time_expression(raw_time)
                result.resolved_filters.append(ResolvedFilter(
                    field_name=partition_field,
                    value=normalized_time,
                    operator="=",
                    resolution_pass=1,
                    original_value=raw_time,
                    confidence=1.0,
                ))
                logger.info(
                    "Time: %s → %s = %s (explore=%s)",
                    raw_time, partition_field, normalized_time, explore_name,
                )

    # ── Mandatory partition filter ──
    partition_field = EXPLORE_PARTITION_FIELDS.get(explore_name, "partition_date")
    user_specified_partition = any(
        f.field_name == partition_field for f in result.resolved_filters
    )

    if not user_specified_partition:
        result.mandatory_filters.append(ResolvedFilter(
            field_name=partition_field,
            value=DEFAULT_PARTITION_VALUE,
            operator="=",
            resolution_pass=0,
            original_value="(auto-injected)",
            confidence=1.0,
        ))
        logger.info(
            "Auto-injected: %s = %s (explore=%s)",
            partition_field, DEFAULT_PARTITION_VALUE, explore_name,
        )

    return result


def format_resolution_report(result: FilterResolutionResult) -> str:
    """Human-readable filter resolution report for debugging."""
    lines = ["Filter Resolution Report", "=" * 40]

    if result.resolved_filters:
        lines.append("\nResolved Filters:")
        for f in result.resolved_filters:
            confidence_bar = "#" * int(f.confidence * 10)
            neg_marker = " [NEGATED]" if f.is_negated else ""
            lines.append(
                f"  {f.field_name} {f.operator} '{f.value}'{neg_marker} "
                f"(pass {f.resolution_pass}, confidence: [{confidence_bar:<10}] {f.confidence:.0%})"
            )
            if f.original_value != f.value:
                lines.append(f"    ← user said: '{f.original_value}'")

    if result.mandatory_filters:
        lines.append("\nMandatory Filters (auto-injected):")
        for f in result.mandatory_filters:
            lines.append(f"  {f.field_name} = '{f.value}'")

    if result.unresolved:
        lines.append("\nUnresolved (need disambiguation):")
        for u in result.unresolved:
            lines.append(f"  {u['field_hint']} {u['operator']} '{u['value']}'")

    looker_filters = result.to_looker_filters()
    lines.append(f"\nLooker filter dict: {looker_filters}")

    return "\n".join(lines)
